name: Deploy OTA Update

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Publish EAS Update
        run: eas update --branch main --message "Automated OTA update from GitHub Actions"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
